name: Build and Push Docker Image

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/nikitaevchuk/gitops-app:latest
            ghcr.io/nikitaevchuk/gitops-app:${{ github.sha }}

      - name: Update Infra Repository
        run: |
          git clone https://${{ secrets.PAT }}@github.com/NikitaEvchuk/gitops-infra.git
          cd gitops-infra
          sed -i 's|image: ghcr.io/nikitaevchuk/gitops-app:.*|image: ghcr.io/nikitaevchuk/gitops-app:${{ github.sha }}|' deployment.yaml
          git config user.name "GitHub Actions CI"
          git config user.email "actions@github.com"
          git add deployment.yaml
          git commit -m "Auto-update image tag to ${{ github.sha }}"
          git push